config/routes.rb
Blog::Application.routes.draw do

  root :to => "authors#index"

  get "authors/forget"
  resources :authors

  resources :posts

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name

  # One to many relationship with posts
  has_many :posts
end

app/models/posts.rb
class Posts < ActiveRecord::Base

  #fields
  attr_accessible :author_id, :blog, :title

  # Validates on save
  validates_presence_of :title, :blog

  # Relationship with author
  belongs_to :author

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Always executes before any methods
  before_filter :get_author

  # Finds the author with the ID stored in the session with the key :current_user_id
  def get_author
    @current_author ||= session[:current_user_id] && Author.find(session[:current_user_id])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @author = Author.new

    @pagetitle = "Welcome to Rails Blog"
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    # Name
    name = params[:author][:name]

    # Fetching author object
    @author = Author.find_or_create_by_name(name)

    # Saves in session
    session[:current_user_id] = @author.id

    # Redicts to posts page
    redirect_to posts_path
  end

  def destroy
  end

  def update
  end

  def forget
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    # Fetches all posts
    @posts = Posts.all
  end

  def show
    #Fetches requested post
    @post = Posts.find(params[:id])

    @pagetitle = @post.title

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @posts = Posts.new
  end

  def edit
    @post = Posts.find(params[:id])

    @pagetitle = 'Edit: ' + @post.title

    # Only actual author can edit this post
    if @post.author_id != @current_author.id
      redirect_to @post, notice: 'Sorry, you do not have permission to edit this post.'
    end
  end

  def create
    @post = Posts.new(:title => params[:posts][:title], :blog => params[:posts][:blog], :author_id => @current_author.id)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was created' }
      else
        format.html { redirect_to posts_new_path, notice: 'Post was not created, please make sure you filled out all the fields.' }
      end
    end
  end

  def update
    @post = Posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(:title => params[:posts][:title], :blog => params[:posts][:blog])
        format.html  { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit", :notice => 'Post was not updated.' }
        format.json  { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    # Fetches post
    @post = Posts.find(params[:id])

    # Only actual author can delete this post
    if @post.author_id != @current_author.id
      respond_to do |format|
        format.html { redirect_to posts_path, :notice => 'Sorry, you do not have permission to delete this post.' }
      end
    else

      #deletes post
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_path, :notice => "Post was deleted." }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb <%= @author.id %> : <%= @author.name %></p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<div class="well">
  <h1>Welcome to Rails Blog</h1>

  <% if @current_author.present? %>

    <!-- Welcome back message -->
    <p class="lead">
      Welcome back <%= @current_author.name %>... <%= link_to "start blogging now!", posts_path %>
    </p>

    <!-- Not this person message -->
    <p>
      <%= link_to "Not " + @current_author.name + "?", authors_forget_path %>
    </p>

  <% else %>

    <!-- Welcome Message -->
    <p class="lead">
      To start blogging just enter your name below:
    </p>

    <!-- Login Form -->
    <%= form_for @author do |f| %>
      <div class="control-group">
        <%= f.label :name %>
        <div class="field">
          <%= f.text_field :name, :class => "span5" %>
        </div>
      </div>
      <%= f.submit 'Login', :class => "btn btn-primary" %>
    <%end %>

  <% end %>

</div>

<p>
  Don't want to login? Click to <%= link_to "view the blogs", posts_path %>.
</p>

app/views/authors/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/authors/new.html.erb</p>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><% if @pagetitle.present? %><%= @pagetitle %> | <% end %>Rails Blog</title>
  <meta id="viewport" name="viewport" content="width=device-width; initial-scale=1; maximum-scale=1; user-scalable=0;" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Rails Blog", posts_path, :class => "brand" %>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          <% if @current_author.present? %>
            Hi <%= @current_author.name %>!
          <% end %>
        </p>
        <ul class="nav">
          <li><%= link_to "Home", root_url %></li>
          <li><%= link_to "Blog", posts_path %></li>
          <% if @current_author.present? %><li><%= link_to "New post", :controller => "posts", :action => "new" %></li><%end%>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">

  <% if flash[:notice] %>
    <!-- Notice -->
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <%= yield %>

</div><!-- .container-fluid -->
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f| %>

  <div class="control-group">
	  <%= f.label :title %>
	  <div class="field">
	  	<%= f.text_field :title, :class => "span10" %>
	  </div>
  </div>

  <div class="control-group">
	<%= f.label :blog %>
	  <div class="field">
	  <%= f.text_area :blog, :size => "20x10", :class => "span10" %>
	</div>
  </div>

  <%= f.submit 'Submit', :class => "btn btn-primary" %>
<% end %>

app/views/posts/index.html.erb
  <% if @posts.empty? %>
    <p class="lead">
      <em>No posts were found.</em>
    </p>
  <% else %>
    <div id="container">
      <% @posts.shuffle.each do |post| %>
        <div class="box">
          <h4><%= link_to post.title, post %></h4>
          <p><%= truncate post.blog, :length => [*20..100].sample %></p>
          <p>
            <%= link_to "Show", post, :class => "btn btn-small btn-info" %>
            <% # Checks if this blog was written by current author %>
            <% if @current_author.present? && post.author_id == @current_author.id %>
              <%= link_to "Edit", edit_post_path(post), :class => "btn btn-small" %>
              <%= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small" %>
            <% end %>
          </p>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/posts/new.html.erb
<h1>New Blog Entry</h1>

<%= form_for :posts, :url => posts_path do |f| %>

  <div class="control-group">
	  <%= f.label :title %>
	  <div class="field">
	  	<%= f.text_field :title, :class => "span10" %>
	  </div>
  </div>

  <div class="control-group">
	<%= f.label :blog %>
	  <div class="field">
	  <%= f.text_area :blog, :size => "20x10", :class => "span10" %>
	</div>
  </div>

  <%= f.submit 'Submit', :class => "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<!-- Title -->
<h1><%= @post.title %></h1>

<!-- Details -->
<p class="muted">Posted on <%= @post.created_at.strftime("%d %b %Y at %I:%M%p") %></p>

<!-- Blog -->
<div class="blog">
<%= simple_format @post.blog %>
</div>

<!-- Buttons -->
<p>
  <% if @current_author.present? && @post.author_id == @current_author.id %>
    <%= link_to "Edit", edit_post_path(@post), :class => "btn" %>
    <%= link_to "Delete", @post, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
  <% end %>
  <%= link_to 'See all posts', posts_path, :class => "btn btn-info" %>
</p>